### ISSUE TITLE
FIx this

### ISSUE THREAD

**Issue by DanishShah** [TheProgrammersClub/err_404#13]
-landing animation should be delayed.
-switch prizes and sponsors section (white with black and vice versa).
-flipping animation on venue section causing the map problem.
-fix the gfx of schedule section.
-if possible keep all the section with text on black bg and rest on white(same as it was before)

**Comment by afzalsayed96** [comment]
Can delay the animation in GIF itself for landing page

**Comment by afzalsayed96** [comment]
Added 2 sec delay in landing animation GIF

**Comment by afzalsayed96** [comment]
Why is it not reflecting?

**Comment by jawadsh123** [comment]
@afzalsayed96 the changes are now reflected.
@DanishShah what is to be fixed in the schedule? I feel the colours and the nav bar needs to be chaged.
may be you can you look into choosing the color scheme for it?
I dont like prize on black too, but should sponsors really come so above in the page?
I'll look into the reordering though.

**Comment by DanishShah** [comment]
schedule seems good now
